### ISSUE TITLE
Is it better to have a copy of the BLAS library as part of the source code?

### ISSUE THREAD

**Issue by metabench** [nperf/nblas#1]
The current method looks best for when lblas is already installed.

Including the source code and building that with the addon would make it easier to install through npm.

Would it be worth referencing a version of lblas that gets compiled alongside the plugin when lbas is not already installed on the system?

**Comment by mateogianolio** [comment]
In OSX it was preinstalled, is it the same for Windows?

**Comment by metabench** [comment]
I don't know for sure but I doubt it.

How about Linux distros as well?

**Comment by waylonflinn** [comment]
Requiring a pre-installed BLAS seems reasonable. On Ubuntu, I use [OpenBLAS](http://www.openblas.net/) and it's likely that the people who are interested in this sort of thing will already have their favorite BLAS installed. It might be nice to survey the options and try to make good recommendations for each platform.

**Comment by metabench** [comment]
@waylonflinn The use case I have in mind is for when the library gets installed when it's a requirement of other systems, rather than for a mathematician/developer audience who would be more familiar with BLAS, and how its installation would fit in with this component. I see it as advantageous if this library, or others that require it, do not require anything to already be on the system apart from the standard node/npm tools.

By compiling the C++ BLAS code rather than requiring it to already be installed on the system, this (and Vectorious, which makes use of it) would better fit into tools that are more general purpose in intent but make use of highly optimized BLAS code. There is a huge difference in ease of use when comparing using npm to install something and it runs in an optimal way, and having to ensure a particular library has already been installed.

A best-of-both-worlds may be possible. During the installation process it could detect whether the system already has BLAS installed, and if it's not found, compile a local version of it. I don't know the details of how it would work, but it's possible to run scripts during the installation of npm modules (see https://docs.npmjs.com/misc/scripts).

Another possibility would be during installation to always compile a local version of BLAS. It would then only use that if it can not load the non-local version.

**Comment by mateogianolio** [comment]
I’m starting to lean towards building openblas if no local blas installation is found. The only problem is it would add significant time to the installation process. Also, not sure how to solve compilation on Windows.
