### ISSUE TITLE
Node.js 12 compatibility

### ISSUE THREAD

**Issue by ccope** [nperf/nblas#19]
It appears that V8 has changed APIs for several of its types. You might want to look into [NAN](https://github.com/nodejs/nan) (probably the lowest effort) or N-API (only supports Node.js v10+)

**Comment by mateogianolio** [comment]
Thanks for the info, I'll check out nan again. Hopefully they have a more stable API now... (I deliberately chose not to use nan before, see #4). I will also look into the API changes and see if they are breaking or if I can push a backwards-compatible fix without using nan.
