### ISSUE TITLE
Deprecated v8 references

### ISSUE THREAD

**Issue by lbordowitz** [nperf/nblas#29]
Here are the errors I've encountered:

```
npm ERR! In file included from ../routines/level1/dot.cc:2:
npm ERR! ../routines/level1/dot.cc: In function ‘void ddot(const v8::FunctionCallbackInfo<v8::Value>&)’:
npm ERR! ../lib/routines.h:7:46: error: ‘class v8::ArrayBuffer’ has no member named ‘GetContents’
npm ERR!     7 | (static_cast<unsigned char*>(view->Buffer()->GetContents().Data()) + view->ByteOffset())
npm ERR!       |                                              ^~~~~~~~~~~
npm ERR! ../routines/level1/dot.cc:6:53: note: in expansion of macro ‘GET_CONTENTS’
npm ERR!     6 |         const double *x = reinterpret_cast<double*>(GET_CONTENTS(info[1].As<v8::Float64Array>()));
```
... and many more like that.

Also:

```
npm ERR! In file included from ../src/index.cc:1:
npm ERR! /home/larry/.cache/node-gyp/19.4.0/include/node/node.h:993:7: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!   993 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /home/larry/.cache/node-gyp/19.4.0/include/node/node.h:1027:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!  1027 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/index.cc:121:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!   121 | NODE_MODULE(addon, Init)
npm ERR!       | ^~~~~~~~~~~
```

Currently, the npm package refers to `GetContents`, but my compiler is very eager to tell me `‘class v8::ArrayBuffer’ has no member named ‘GetContents’`. As mentioned in [this SO post](https://stackoverflow.com/questions/69290893/getcontents-in-v8arraybuffer), this has been replaced with the [`GetBackingStore` function](https://v8.github.io/api/head/classv8_1_1ArrayBuffer.html#aaa29e281f94990cbf0a5484140fffb50).

Additionally, it looks like `node::addon_register_func` has had its function signature changed, and now requires two additional parameters.

Everything I know about bindings I learned in the last fifteen minutes trying to gather enough information for this issue to be intelligible.

**Comment by mateogianolio** [comment]
Sorry for the slow response and thank you for creating the issue! Long time ago I tested this package so makes sense that some features have been deprecated in new node versions. I will investigate when I have time.

**Comment by mateogianolio** [comment]
@lbordowitz I'm not sure about your second issue (with the `NODE_MODULE`-macro). I have tried building in node 16, 18 and 19 and works in all three without a single warning or error. Do you still get the warning/error with the latest version?

A possible fix is to change 

```cpp
NODE_MODULE(addon, Init)
```

... to...

```cpp
NODE_MODULE(NODE_GYP_MODULE_NAME, Init)
```

... but I don't think it makes any difference.

**Comment by mateogianolio** [comment]
@lbordowitz Nevermind, now I see it's just a gcc warning (see https://github.com/nodejs/nan/issues/807). Leaving this closed. Hope it works for you now :)
